os:
- linux
language: node_js
node_js:
- 10
dist: xenial
before_install: cd web-api
jobs:
  include:
  - name: test web api
    script: npm run test
  - name: deploy
    deploy:
      provider: heroku
      api_key:
        secure: c8hSALdLhDuubkLZsVuwEnQOV40lIvPJsCa85Qa4Fx72VTEgUipb18dI8U5GSG5oujpangLxJrtZwoEV3GVrCjyyQpkLgInryV/HKL3cRI/9143ZOZoKbGvgLd0TjFKHMR9HDJSC8Rk2A8uVSYt7s25v6b9nO04tCcsXajscXmJG4tCID28N0G/nBNvvrTSrSFQuMQvoEZRdGXISFvjpJnHiX9EcPCnVIJYxhvkBpteKM/Fxt2Z4eWI4T+P6m5BBNglpBEEoKVItltyD51sXbMv2S3zfjtaHB7hj2WUd8Vy4yTg8o5zeRMBI8ORWqm44CqMnmYJzkH+sNirYHLfjP8Uu0Lmul+W+9BVAB6QwZ6zL2KtjLLHYa3IQv8vSvPPf7EWA3dbtttZn+V0vIyRUodngvulo6OoDwt9F89UHCwgCxzEyVQ7rO0aL5RHbNkZy4IZuOUSu8HWF8esp6dna8pMj2SvmxNu/HsR9+UaBNAeO9+hs8eCxHpTO4IjZY77jRD7/GsVMBaSKvJT41ceLM56El0mp3+TuvMzhMHGuNcKot37pHX022naeY1EKrvzrTF9lTHyR3SHWr5s1YO7/Surpot/BSy4nBXiLzC11AgJ4KqwqSLkVCFPK1jAPln2yDOD7efFh9QcFfkArUFEV3tesp3DYhwBPEVNnk4rmkNQ=
      app: web-api
      on: webapimaster
deploy:
  api_key:
    secure: cfmsAONnnzRI9BZa9Ve6DX5C2uDwPR8jVXDWKs7eegC503gaGdM0u2yfJ8S2LqF4U2bOEDhdsWl2iUZmtVesiWgwCVrdKIx1Plb3AhqSBYyasdQ2kLBQ0kAEHuavJDut8jH3Iglc5otWsC84PyPr1pRATXDI6VPK3xhTg3o0Ko9NRpjrpL9ZWUFeyicnvRYPUiPkEmxvpWIPwg3vfCE+c/9fhOTjnA5QocblyKtjvlZh7h3Ol4//lDH5IwJG8FERRjWTQDI+tf6MoR02PBmevM1LwTOsx37RO3lUknBXfeQTgHHcQ4WQNCf0j+l34cik8euOdO5lWjOr30+tFlFCg7DwArVwFe9ivzF32fY/kzbzzSCa+K9Z6OwMt3XID+OD2/8XLpSnd/n6zKb2UIGxEG99zmlnpFlprLbzPHunrt7wjfGMUINsG9cXVIeadycpXad4VTAHOxJs4wdmSB1AMmJ4XVXpVaAIQC2IHdOazb2VOanXGsV+G23XmN6C3+RzOxcrYXDjhwqx3I6l1U4VsbteT16CLRKiAKJWeXnuQeuD2IXox20Vs1xYQyjh72z9dGt91uJhSf3dZY3WTElTok69P/o5n5lmjZxmWKBiu8rTPVKLpLmPiRghGeP4AP9zTbZbloHJqAqJWiHXhqXd5Jf136mgluB++w60pjQBbr8=
