os:
- linux
language: node_js
node_js:
- 10
dist: xenial
before_install: cd web-api
jobs:
  include:
  
  - name: test web api
    script: npm run test
  
  - name: deploy
    deploy:
      provider: heroku
      api_key:
        secure: ACcGbZ84yAozN550ht3smU1Ewm6Xgnr5thB4ehB5GJ1r6ASDhjtJqwBeq0YZIpv9xfalGYeILf0NLgfwBrp/hJR7+5/uwxR276quWQ2NGcnGPBAPFxC2MGZCwOb8WMtzRHohhjbfTTBdzNiLzfMAZ4LMLtVQtd5eqTaG55KkZ9ee3mKTL1W6bmNzzYsfuLHqs64lqbGWt9lbRUHjf3KFDaDQJDZLvUZces8KmenmcS6y5Kku92xF9KJZ9dCUv3noZQ8D0jdjiuBwVWpoYkjcA3GJ81/B0YdYdpyTvxU/o5JYy+fRlk6mf364OLAuyrkDBAVtdFoSH7Nm+roI+BFX8Leslz0CSJvVCjH6LscQJrm2hkX9bsQuoeW+BELRoXVbmW6kjZMl84P+sYYWiRsqyxaPnAiri0lFGbeBylbbNIRTOhCz+YI/nvEAcR/IA5bL2lgc1X7EGPGIMPH6EYStocOWRtoNdW9iVsQ8GxBgRNqVPYLTCY3JI2JBXoHQs5jHMG4jqh39+UPii+9veQg8Zj9VzipeAwlyRXnsmTLUTIStM6Wzdsx2VRfin8BwZDDCZNrjpjRoAfBeQhuG4nLQ65Zb+su++OFiY8UQgjAGbDj9BFnjYRbrCiSxc48LN4AtrwDo/VWLZZpaSF49RcRfDSDnH7u8ZxZ8O6mCNuy8Igg=
      app: pfe-e2020-noan
      on: webapimaster