os:
- linux
language: node_js
node_js:
- 10
dist: xenial
before_install: cd web-api
jobs:
  include:
  
  - name: test web api
    script: npm run test
  
  - name: deploy
    deploy:
      provider: heroku
      api_key:
        secure: LHvoT6gWI1k2bTHbbMqOsrPb7z9A75Aph6LlSHpvqDg8sKy9tL5ZUKhtrzyv2tkLOWPUMubDTXmJ0LnvEea1FTDdHHbAL+ugzIIXdVWf+m0/uz9JC+bFZ+cpbxGzFNN6Zz5l4ubACDgUMzu84qxPdrEe18vsTGCyRHwhwh5rKYpjbPJi3+M1yq5DO6P36vnRln6XtdDJ2IudPArWvbCOwATe7eEsth1scVPpzuxKOv2nOMlTE0eHoIDrf5iE++ag8c82dZMGvKNvZmq1kCamAlanPTVKutZ4YC1XN9Og54yf9D1S8zwFvVkYBPw/Xdcn050hWTPmE3Jv6XjRVG+GCaEgNY9RCeUM+mSsPMG+YulEnOIlSEG4Y7GM1Z2ooEe8f8f0Ya3LiILL/ZcYq3YZNMnypUGsG61Rc1p4X11TEqoFjM/Z13llaGTgSBkKTuZVLXQil+WZt2fu9Fa9Hiwy+suw6xU/hz33QV5BENBFBqmV1EuKBrrILk/wXfJdX76HvyhOKSiDB50DSNfGrOCuCzkNsf8Hq1P4WobsaPgpoCGHe6fzsCBpycEAZduAWMfhFuV9EbeuT3fnOX5kzM2rUO4VE7WSyESLnJ2K+zgY+j5dAXFOM16KeP7Dcj+C4XhRszk51RukCUmRg5ktgfxM68088t4Pi1LEme6Bw0F4pCA=
      app: pfe-e2020-noan
      on: webapimaster