os:
  - linux
language: node_js
node_js:
  - 10
dist: xenial

before_install: cd web-api

jobs:
  include:

    - name: test web api
      script: npm run test

    - name: deploy
      deploy:
        provider: heroku
        api_key:
          secure: a9fb9863-2308-4e74-bcda-87ce4b54dd00
        app: web-api
        on: webapimaster